### ISSUE TITLE
Failed to load on macOs M2:  mindaro.mindaro  incompatible architecture (have 'x86_64', need 'arm64')

### ISSUE THREAD

**Issue by pmunin** [Azure/vscode-bridge-to-kubernetes#102]
**Describe the bug**
Error & Warning while starting vscode, during "Kubernetes: update dependencies...":
```
Failed to load /Users/<USERNAME>/Library/Application Support/Code/User/globalStorage/mindaro.mindaro/file-downloader-downloads/dotnet/host/fxr/7.0.7/libhostfxr.dylib, ... (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

Kubernetes Clusters list displayed empty - it was just working couple of days ago, picking it up from $KUBECONFIG list.

I have explicitly installed .net core 7 and 8 for macOs - didn't help

```
💬 dotnet --list-sdks
7.0.306 [/usr/local/share/dotnet/sdk]
8.0.101 [/usr/local/share/dotnet/sdk]

💬 dotnet --list-runtimes
Microsoft.AspNetCore.App 7.0.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 8.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 7.0.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 8.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

Following ["Workaround"](https://github.com/microsoft/mindaro/issues/32) didn't help

**Mention the platform you are using**
MacOs, Chip: Apple M2, Sonoma 14.3 (23D56)

**To Reproduce**
1) Install Bridge to Kubertenes vscode extension
2) Restart vscode

**Expected behavior**
Kubernetes clusters are picked up from $KUBECONFIG

**Screenshots**

![image](https://github.com/Azure/vscode-bridge-to-kubernetes/assets/7120440/d9e38708-c632-435e-a5a2-96ded62eea62)

![image](https://github.com/Azure/vscode-bridge-to-kubernetes/assets/7120440/9e30469e-571f-4e95-9afa-d9b9d4b09cda)

![image](https://github.com/Azure/vscode-bridge-to-kubernetes/assets/7120440/4e5092a6-5f6e-4b08-8772-a14422cca72a)

**Desktop (please complete the following information):**
Version: 1.86.0 (Universal)
Commit: 05047486b6df5eb8d44b2ecd70ea3bdf775fd937
Date: 2024-01-31T10:29:15.765Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.3.0

**Additional context**

Logs:
```
2024-02-02T12:23:54.929Z | Common Extension Root    | ERROR | Error: cli-client-get-version-error <json>{}</json> <stack>Error: Failed to load /Users/<USERNAME>/Library/Application Support/Code/User/globalStorage/mindaro.mindaro/file-downloader-downloads/dotnet/host/fxr/7.0.7/libhostfxr.dylib, error: dlopen(/Users/<USERNAME>/Library/Application Support/Code/User/globalStorage/mindaro.mindaro/file-downloader-downloads/dotnet/host/fxr/7.0.7/libhostfxr.dylib, 0x0001): tried: '/Users/<USERNAME>/Library/Application Support/Code/User/globalStorage/mindaro.mindaro/file-downloader-downloads/dotnet/host/fxr/7.0.7/libhostfxr.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/<USERNAME>/Library/Application Support/Code/User/globalStorage/mindaro.mindaro/file-downloader-downloads/dotnet/host/fxr/7.0.7/libhostfxr.dylib' (no such file), '/Users/<USERNAME>/Library/Application Support/Code/User/globalStorage/mindaro.mindaro/file-downloader-downloads/dotnet/host/fxr/7.0.7/libhostfxr.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))\nThe library libhostfxr.dylib was found, but loading it from /Users/<USERNAME>/Library/Application Support/Code/User/globalStorage/mindaro.mindaro/file-downloader-downloads/dotnet/host/fxr/7.0.7/libhostfxr.dylib failed\n  - Installing .NET prerequisites might help resolve this problem.\n     https://go.microsoft.com/fwlink/?linkid=2063366\n\n    at ChildProcess.<anonymous> (/Users/<USERNAME>/.vscode/extensions/mindaro.mindaro-2.0.120240111/src/clients/CommandRunner.ts:99:28)\n    at ChildProcess.emit (node:events:514:28)\n    at ChildProcess.emit (node:domain:489:12)\n    at Process.onexit (node:internal/child_process:291:12)</stack>
2024-02-02T12:23:54.931Z | Common Extension Root    | ERROR | Error: binaries-utility-ensure-binaries-error <json>{"isUsingLocalBinaries":"false","isUsingLocalDotNet":"false"}</json> <stack>Error: Failed to load /Users/<USERNAME>/Library/Application Support/Code/User/globalStorage/mindaro.mindaro/file-downloader-downloads/dotnet/host/fxr/7.0.7/libhostfxr.dylib, error: dlopen(/Users/<USERNAME>/Library/Application Support/Code/User/globalStorage/mindaro.mindaro/file-downloader-downloads/dotnet/host/fxr/7.0.7/libhostfxr.dylib, 0x0001): tried: '/Users/<USERNAME>/Library/Application Support/Code/User/globalStorage/mindaro.mindaro/file-downloader-downloads/dotnet/host/fxr/7.0.7/libhostfxr.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/<USERNAME>/Library/Application Support/Code/User/globalStorage/mindaro.mindaro/file-downloader-downloads/dotnet/host/fxr/7.0.7/libhostfxr.dylib' (no such file), '/Users/<USERNAME>/Library/Application Support/Code/User/globalStorage/mindaro.mindaro/file-downloader-downloads/dotnet/host/fxr/7.0.7/libhostfxr.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))\nThe library libhostfxr.dylib was found, but loading it from /Users/<USERNAME>/Library/Application Support/Code/User/globalStorage/mindaro.mindaro/file-downloader-downloads/dotnet/host/fxr/7.0.7/libhostfxr.dylib failed\n  - Installing .NET prerequisites might help resolve this problem.\n     https://go.microsoft.com/fwlink/?linkid=2063366\n\n    at ChildProcess.<anonymous> (/Users/<USERNAME>/.vscode/extensions/mindaro.mindaro-2.0.120240111/src/clients/CommandRunner.ts:99:28)\n    at ChildProcess.emit (node:events:514:28)\n    at ChildProcess.emit (node:domain:489:12)\n    at Process.onexit (node:internal/child_process:291:12)</stack>
2024-02-02T12:23:54.931Z | Common Extension Root    | WARNG | Failed to update dependencies <json>{}</json> <stack>Error: Failed to load /Users/<USERNAME>/Library/Application Support/Code/User/globalStorage/mindaro.mindaro/file-downloader-downloads/dotnet/host/fxr/7.0.7/libhostfxr.dylib, error: dlopen(/Users/<USERNAME>/Library/Application Support/Code/User/globalStorage/mindaro.mindaro/file-downloader-downloads/dotnet/host/fxr/7.0.7/libhostfxr.dylib, 0x0001): tried: '/Users/<USERNAME>/Library/Application Support/Code/User/globalStorage/mindaro.mindaro/file-downloader-downloads/dotnet/host/fxr/7.0.7/libhostfxr.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/<USERNAME>/Library/Application Support/Code/User/globalStorage/mindaro.mindaro/file-downloader-downloads/dotnet/host/fxr/7.0.7/libhostfxr.dylib' (no such file), '/Users/<USERNAME>/Library/Application Support/Code/User/globalStorage/mindaro.mindaro/file-downloader-downloads/dotnet/host/fxr/7.0.7/libhostfxr.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))\nThe library libhostfxr.dylib was found, but loading it from /Users/<USERNAME>/Library/Application Support/Code/User/globalStorage/mindaro.mindaro/file-downloader-downloads/dotnet/host/fxr/7.0.7/libhostfxr.dylib failed\n  - Installing .NET prerequisites might help resolve this problem.\n     https://go.microsoft.com/fwlink/?linkid=2063366\n\n    at ChildProcess.<anonymous> (/Users/<USERNAME>/.vscode/extensions/mindaro.mindaro-2.0.120240111/src/clients/CommandRunner.ts:99:28)\n    at ChildProcess.emit (node:events:514:28)\n    at ChildProcess.emit (node:domain:489:12)\n    at Process.onexit (node:internal/child_process:291:12)</stack>
```

**Comment by hsubramanianaks** [comment]
@pmunin Thanks for raising this issue, can you follow this workaround - https://github.com/Azure/Bridge-To-Kubernetes/issues/350#issuecomment-1889706656 and see if it works ? Thank you.
